# docker基础镜像 - locust运行镜像
#
# date 2019-11-27
# author naturezhm
# version 1.0

FROM locustio/locust:2.5.1
LABEL maintainer="naturezhm@gmail.com"


ARG APP_VERSION=1.0

ENV APP_VERSION=${APP_VERSION}


