apiVersion: v1
kind: Service
metadata:
  name: monkey-locust-master-svc
  namespace: boomer
  labels:
    app: monkey-locust-master
spec:
  type: ClusterIP
  selector:
    app: monkey-locust-master
  ports:
  - name: locust1
    protocol: TCP
    port: 5557
    targetPort: 5557
  - name: locust2
    protocol: TCP
    port: 5558
    targetPort: 5558
  - name: locust3
    protocol: TCP
    port: 8089
    targetPort: 8089
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    deployTime: '${deployTime}'
  name: monkey-locust-master
  labels:
    app: monkey-locust-master
    deployTime: '${deployTime}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monkey-locust-master
  template:
    metadata:
      labels:
        app: monkey-locust-master
        deployTime: '${deployTime}'
    spec:
      containers:
      - name: monkey-locust-master
        image: ${DOCKER_IMAGE}
        imagePullPolicy: Always
        tty: true
        stdin: true
        ports:
        - containerPort: 5557
        - containerPort: 5558
        - containerPort: 8089
        env:
        - name: LOCUST_DUMMY
          value: "/locustfile.py"
        - name: OUT_FILE
          value: "result"
      imagePullSecrets:
        - name: docker-password
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/service-weight: ''
  name: monkey-boomer-svc
  namespace: boomer
spec:
  rules:
    - host: boomer.dev.supermonkey.cc
      http:
        paths:
          - backend:
              service:
                name: monkey-locust-master-svc
                port:
                  number: 8089
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - boomer.dev.supermonkey.cc
      secretName: internal-supermonkey-cc-cert

      